### ISSUE TITLE
Enable settings

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise_wms#13]
## Context
The settings 
`group_product_variant`
`group_stock_packaging`
need to be enabled to work with packages in the inventory app of odoo.

## ToDo
Enable them when the boxwise_WMS module is installed.

**Comment by HaGuesto** [comment]
Helpful Links:

- https://www.odoo.com/es_ES/forum/ayuda-1/question/how-to-change-settings-on-module-installation-72694
- https://stackoverflow.com/questions/31162964/how-to-change-settings-on-module-installation/31199994

**Comment by jamescrowley** [comment]
I haven't been able to make much progress on this. It's not clear to me when the appropriate time to 'set' these existing fields are, and I haven't been able to get any Google-d examples actually working in my Odoo environment.

Some of the ways I looked at:
- Setting via a data record - couldn't find a permutation that worked (it just silently did nothing), and haven't yet figured out how to debug how these are applied so I could see what *was* getting set
- Extending the TransientModel class for res.config.settings - would allow you to extend the UI for new fields, but can't see how this enables us to set existing ones at install/upgrade time (as opposed when someone is actually editing the settings).
- Using a function called from that data files, which in theory might be able to 'set' the value. But again couldn't find any clear docs on this and felt like it would be very hacky.

**Comment by HaGuesto** [comment]
## New material 
Check out the (cookbook)[https://drive.google.com/file/d/1NjoIp93tHKp5gjBdxjhNx2MyZXfH4yjL/view?usp=sharing] p. 310 and following
