### ISSUE TITLE
Update attributes and attributes.values

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise_wms#18]
Simplify and consolidate the existing attributes so that these are the only top level attributes

- Gender
- Age group
- Shoes sizes
- Bra sizes
- Diaper sizes
- Clothing sizes

**Comment by HaGuesto** [comment]
This issue is taken already by @naphets123.

**Comment by HaGuesto** [comment]
@naphets123

**Comment by jamescrowley** [comment]
While there are still issues with the import, the basic structure for Pampiraraki is done
