### ISSUE TITLE
Update user flow for incoming donations

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise_wms#22]
![user flows](https://user-images.githubusercontent.com/29065125/52160331-0ae10a80-26b4-11e9-91ae-c4d1ab1d3906.png)

## comments for possible changes

- 1st step: I do not understand what you mean with overflowing items.
- 2nd step: Do you mean you look for sorting boxes that are overflowing. The description "pick a size that seems big enough" is a bit misleading.
- 5th step "Write information on label ....": During my time we first registered the box in the system and then wrote the label. Why? Because you should write the exact same name of the product as in the system. If you first write the label the name on the box and in the system tend to diverge.
- 10th step " Walk to the pallet matching the first ....": Maybe we should offer here two possibilities. Nea Kavala is actually the only warehouse which is sorted by numbers. The other ones are sorted by category.

**Comment by DurkoMatko** [comment]
10th step: The **"package code"** mentioned here is actually the **"box number"** from the 9th step? Maybe it'd be better to use the consistent term. I guess this workflow will be the really useful for people who never done this before (like me) and this 10th step got me thinking for a sec. 

If I didn't get it right and package code is something different than box number, could someone explain it to me? :D Thx!

**Comment by HaGuesto** [comment]
@jamescrowley 
Could you please add two swimlanes for the two user groups in #29 horizontally in this diagram? You probably have to move it around a bit.

**Comment by jamescrowley** [comment]
@HaGuesto regarding your points above:
* 1st/2nd step: overflowing items. this was reference to how we pre-sorted in Nea Kevala when I was there.  ‘staging’ boxes were filled first with items sorted by category but not by size. then once those are overflowing, sort by sizes and pack away the sizes that are big enough to fill a box. I'll use your 'sorting boxes' terminology
* 5th step: I saw these done both ways, depending on whether 'one' person was doing the tech bit, or everyone was (otherwise other volunteers wrote the labels and left the 'tech' person to scan)

**Comment by jamescrowley** [comment]
Exploded somewhat but attempted to capture the feedback.

The aim for now is for this to reflect *current* workflows in practice, rather than desired. I've put hypothetical (as far as Boxwise is concerned) warehouse set ups in too, but greyed out. 

Also added some terminology - @HaGuesto perhaps we should document to align business terminology in code/app/descriptions.

Thoughts? Does it reflect everyone else's experiences in how the app has been used so far? Anything I've missed or can be simplified? We should obviously then discuss how we'd *like* it to work :D

![user flows v2](https://user-images.githubusercontent.com/509533/52669641-d886a700-2f16-11e9-8f20-a8c1428db587.png)

**Comment by HaGuesto** [comment]
@jamescrowley Amazing! 

## Let's start with terminology:

1. A category according to your definition is a product for me. 
2. size/sizes are variants of the product.
3. A category would be something like clothing or food (maybe also bottoms or shoes) for me.  
If we use this terminology we stay close to the odoo one and that's a def a plus to make everything less confusing.

## Process:

1. I would summarize the first few steps. Every warehouse will have a bit of a different process to sort. I do not think that we will manage to standardize that. Our starting point should be "Sorted donations are counted and put into a box" or similar.
(2. not important atm. The start might be interesting the moment the organizations would like to track where their donations are coming from, e.g. a private donor or company donation form mango or zara. ) 
3. We can actually print the Bonumber already on the labels whe they are printed. Do you think we should do that? In the process described above it is a bit of a control mechanism. If there is a box with no boxnumber on it, you know that something went wrong.

**Comment by jamescrowley** [comment]
> 3. We can actually print the Bonumber already on the labels whe they are printed. Do you think we should do that? In the process described above it is a bit of a control mechanism. If there is a box with no boxnumber on it, you know that something went wrong.

Interesting. I guess that means that currently we couldn't adapt the allocation strategy so easily? For instance, if the warehouse was organised by number, and you wanted to get smarter about allocating to emptier sections of the warehouse - would only really make sense to allocate once the box is filled as opposed to when the labels are printed?

**Comment by jamescrowley** [comment]
> * size/sizes are variants of the product.
As I understand from the Odoo documentation, a variant is a unique combination of attributes attached to the product? So assuming multiple attributes, size on it's own is an attribute. But a product 'shoes' with attributes size: L, gender: M is a variant?

**Comment by jamescrowley** [comment]
![create new box](https://user-images.githubusercontent.com/509533/52785994-e1cc5c80-3059-11e9-819a-62100a293e5c.png)

**Comment by HaGuesto** [comment]
> Interesting. I guess that means that currently we couldn't adapt the allocation strategy so easily? For instance, if the warehouse was organised by number, and you wanted to get smarter about allocating to emptier sections of the warehouse - would only really make sense to allocate once the box is filled as opposed to when the labels are printed?

You are right. 
A smarter allocation is just an enhancement for now. However, if we drop the actual process of writing down the box number and just print the number on the labels we will not be able to do this enhancement.

Probably we should stick then with the old process and still write the number on the label by hand.

**Comment by HaGuesto** [comment]
> As I understand from the Odoo documentation, a variant is a unique combination of attributes attached to the product? So assuming multiple attributes, size on it's own is an attribute. But a product 'shoes' with attributes size: L, gender: M is a variant?

Again you are right :) Please use your definitions.

Unrelated @jamescrowley 
I'm questioning if we should make gender an attribute. I checked out recently how the big clothes companies like [H&M}(https://www2.hm.com/en_gb/index.html) organize their websites. 
They use the genders as THE top product categories. 
Should we reorganize our categories, too? They probably put a lot of research in how to find the right  clothing product the fastest. Maybe we should adopt that?
maybe we should start a separate issue for this :)

**Comment by jamescrowley** [comment]
I'd be reluctant to mandate Gender as being a top level category. Even ignoring the right of any gender to wear whatever the hell they like... in New Kevala at least, vast numbers of child & adults shoes, T-shirts and shirts were easily unisex by traditional standards too. When sorting in Nea Kevala it became a bit arbitrary... I remember one customer was very pleased when he found new shoes that fit him in the women section :)

**Comment by HaGuesto** [comment]
Alright @jamescrowley could you update the last definitions in your process flow and then we can close this issue I think.

**Comment by jamescrowley** [comment]
![incoming donations](https://user-images.githubusercontent.com/509533/52898091-0ea77d80-31da-11e9-9b01-b974af9e7ace.png)
