### ISSUE TITLE
Create Box number / Change odoo package sequence

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise_wms#24]
## Context
Each box / package in Boxwise needs to have a random boxnumber / ID. 
**Why?**
We want to offer our users another possibility of how to organize their warehouse. Often they order their boxes by the product inside. However, if storage space is small it is not the most efficient way to store your stock.Therefore, we offer them also a random number for each Box. With this number they can also organize their stock, eg. each palette/corner in the warehouse corresponds to the first two digits of the Box number.

## Idea
We decided to change the ID number creation in odoo instead of adding another boxnumber field to `stock.quant.package`.

## ToDos:
- [ ] Add an option in the sequence setting `Settings \ Technical \ Sequences & Identifiers \ Sequences` for `stock.quant.package`` to generate random numbers. This setting should be at first some kind of toggle switch to turn random number generation of and on.
Other possibility would be to create another sequence settings menu in inventory as is done in the HR module referenced below.
![image](https://user-images.githubusercontent.com/29065125/52206973-3adb0a00-287c-11e9-875f-26c248977f10.png)

- [ ] Program a random ID generator.

## Useful links:
- You might want to check out [this module](https://github.com/OCA/hr/tree/10.0/hr_employee_id). They created a random ID generator for employee IDs.
- [Here](https://github.com/OCA/hr/blob/10.0/hr_employee_id/models/hr_employee.py) is the python code for the number generation.

**Comment by HaGuesto** [comment]
@DurkoMatko as discussed last Saturday, I marked you on this task.

**Comment by jamescrowley** [comment]
This was completed.
