### ISSUE TITLE
Define personas

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise_wms#29]
## Context
We see at least two personas using Boxwise:
- volunteers and
- coordinators.
(In the future there will also be the head office involved.)

## ToDos:
Describe them!
Most important :
- What are the different needs towards Boxwise?
- How did they surprise us in the past?

Please keep it short and post your description here in this issue for further discussion.

**Comment by jamescrowley** [comment]
Could we call them 'personas' rather than 'user groups'? I think that's typically the term used anyhow. But say if you were thinking otherwise!

Started a draft doc here: https://docs.google.com/document/d/18MeNnzLs1SxUzBG792F3BOyXCbfQsR_dm4E2znwosn8/edit?usp=drivesdk it's for commenting, request access for edit as wasn't sure about posting that in this public issue!

**Comment by jamescrowley** [comment]
(if you object to the Google Doc shout just thought that might be easier to create the initial few revisions that way)

**Comment by HaGuesto** [comment]
@DurkoMatko maybe also nice to get your input on the Google doc. Can you check it out?

**Comment by DurkoMatko** [comment]
@HaGuesto I've added tiny bits which came to my mind, but other than that, I think those persona descriptions fit exactly.

**Comment by HaGuesto** [comment]
@barto74 would you also like to take a look and have some comments for the Google file above.

**Comment by barto74** [comment]
@HaGuesto, this all makes a lot of sense. Good to keep external customer out of scope, however a market/shop manager might actually not be so external (but a customer from another organisation that wants stuff from your warehouse is actually external and its good to keep that out of scope)

**Comment by HaGuesto** [comment]
@barto74 Thanks for the comment! Do you think a shop manager is really different to a coordinator?

@jamescrowley What do u think? Maybe worth adding?

**Comment by barto74** [comment]
@HaGuesto yes it might be a more constrained role. I would identify it, because it brings certain demands (maybe thinking more from a perspective of needs, while the logistics coordinator has to think from a perspective of what is available).

**Comment by HaGuesto** [comment]
@jamescrowley would you mind adding it?

**Comment by jamescrowley** [comment]
Going to close this and create a new issue for updating following Athens.
