### ISSUE TITLE
Create coordinator and volunteer and give them the right permissions 

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise_wms#34]
## Context
We want to simplify the Odoo UI as much as possible for our co-ordinator and volunteer users. The best way of doing this is probably to create user roles for them and assign permissions accordingly.

## Idea
There are 3 aspects we'd like to adjust
- the main navigation elements that appear (this ticket)
- the UI elements that appear when adding/editing a product (#36)
- the UI elements that appear when creating/managing users (#38)

Existing navigation UI looks like this:

![nav_inventory](https://user-images.githubusercontent.com/509533/52936254-e5165f80-335b-11e9-8564-16ffcb4ca208.png)

## ToDo
We want to only show
- the inventory tab (hiding Discuss, Website, Apps and Settings). We may show the "Settings" nav for coordinators only if creating users (#38) looks viable
- within the inventory tab, Products, Product Variants, Packages, Generate QR codes, and the options under "Reports" 

 Everything else hidden.

**Comment by HaGuesto** [comment]
## Useful links:

- The essential book p.77 following
- https://www.odoo.com/documentation/11.0/reference/security.html
- https://github.com/OCA/maintainer-tools/tree/master/template/module/security

@jamescrowley As I see it you can give read rights to users to certain fields. Maybe by that you can directly make them disappear in the views, too.

**Comment by jamescrowley** [comment]
Just for future reference: https://www.odoo.com/forum/help-1/question/hide-menu-for-existing-group-18704 has some useful explanations of the `eval="[(3,ref('my_new_group_id'))]"/>` type syntax that we'd need to use if we end up  needing to remove permissions from the base user roles

**Comment by jamescrowley** [comment]
I'm marking this as done for now but there will be more work in this area.
