### ISSUE TITLE
mobile package info screen

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise_wms#6]
## Context
When a package QR-code is scanned and it is not empty, an infoscreen should be shown.

## Idea

The Info screen should contain:
- boxnumber
- Product Information (category, attributes)
- number of items in the box.
- comments
- last modification of the box and corresponding user.
- last creation date of the box and corresponding user.
- Drop down to show full history of the Box.

## Additional information:
The info screen looked like this before:

![image](https://user-images.githubusercontent.com/29065125/50045043-f8235f80-008c-11e9-8b71-3223b4473d65.png)
![image](https://user-images.githubusercontent.com/29065125/50045049-0a9d9900-008d-11e9-86a5-e51d2339bec2.png)

**Comment by jamescrowley** [comment]
I'm going to close this as we now have this in the prototype albeit with a smaller feature list and a few UI issues.

(Post image here - can't do from mobile without hosting image elsewhere)

Can extend as required later
